#!/bin/bash
#_   _ _____ ___________   _____  ___
#| | | |_   _/  ___| ___ \ /  ___|/ _ \
#| |_| | | | \ `--.| |_/ / \ `--./ /_\ \
#|  _  | | |  `--. \  __/   `--. \  _  |
#| | | |_| |_/\__/ / |     /\__/ / | | |
#\_| |_/\___/\____/\_|     \____/\_| |_/
#Backup all the databases on the current postgres system find there -
#	corrisponding webservers and bakcup the relavent files there and push them to
#	the backup server
#Author	: Renier Rousseau
#Created Date 	: March 2018

#Pull Parameters from the .conf file
source ~/backup.conf

#TODO add exculde list
#TODO work all of the steps into one for loop

##Functions
# 7zip Error Checking
7zipErrorCheck () {
	case "$1" in
		#Exit without Error
		0)
			echo "Zip Success Full"
		;;
		#Exit with Error
		1)
			echo "Non Fatal Error - Not all files where accessable."
		;;
		#Exit with Fatel Error
		2)
			echo "Fatal error"
		;;
		#Exit with Syntax Error
		7)
			echo "Syntax Error"
		;;
		#Exit with Memory Error
		8)
			echo "Not Enough Memory For Operation"
		;;
		#Exit with User Intervention
		255)
			echo "User stopped the process"
		;;
	esac
}

{
  #Header
	echo "---------------------------------------------------------------------"
  echo "      HISP SOUTH AFRICA - Backup Script - Ver 4.0 - March 2018"
  echo "---------------------------------------------------------------------"
	echo ""

  #Time Stamping Starting time
  timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
  echo "$timeinfo > ** Starting Backup of databases **"

  #Time Stamping Starting of Dumps
	timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
	echo "$timeinfo > Step 1: Starting dump of databases"

  #for each database(i) that is not owned by postgres...
	for i in $databases; do
    #Time Stamp for each Database
		timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
		echo "$timeinfo > Database: $i ---------------->"

    #Time Stamp for starting Vacuuming
    timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
    echo "$timeinfo >  - Vacuuming..."
		/usr/bin/vacuumdb --analyze --quiet $i

    #Time Stamp for starting the dunmp
		timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
		echo "$timeinfo >  - Dumping..."
		/usr/bin/pg_dump --jobs=5 --exclude-table=analytics* --format=directory --file=$backup_dir/$i-ddb-$dayinfo $i

    #Time Stamp for Completion of dump.
    timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
    echo "$timeinfo > Dump: $i Complete <----------------"
	done

	#Time Stamping the Start of the webservers backup
	timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
	echo "$timeinfo > Step 2: Starting backup of webserver"

	for i in $database; do
		#Time Stamp for each DB's webserver
		timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
		echo "$timeinfo > Database: $i ---------------->"

		#build the connection string.
		#TODO get ip address - pg-hba.conf
		grep $pg_hba | grep $i | 

		#TODO get tomcat id - look in the /tomcat folder look at dhis.conf
		#TODO build connectiong string to copy files
		#TODO build connection string to get war version. - unzip -q -p webapps/ROOT/WEB-INF/lib/dhis-service-core-2.*.jar build.properties

		#Time Stamp for Completion of backup.
    timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
    echo "$timeinfo > Dump: $i Complete <----------------"
	done

  #Starting the Packaging and encryption
	timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
	echo "$timeinfo > Step 3: Starting pack/encryption and Uploading of databases"

  #for each database(i) that is not owned by postgres...
	for i in $databases; do
    #time stamp for start of encryption
		timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
		echo "$timeinfo >  - Pack/encrypting $i ---------------->"
		#Zipping the files passed.
		7z a -mx=1 -p$encrypt_key $backup_dir/$i-ddb-$dayinfo.7z $backup_dir/$i-ddb-$dayinfo > /dev/null
		7zipErrorCheck $?

		timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
		echo "$timeinfo >  - Uploading: $i ---------------->"
		scp -P $remote_port $backup_dir/$i-ddb-$dayinfo.7z $remote_user@$remote_ip:$remote_dir

    #if its the weekly backup key day then do weekly backup
		if [ "$dayinfo" == $weekly_backup ]; then
      #Time stamp for packing weekly backup
      timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
      echo "$timeinfo >  - (Weekly) Pack/encrypt..."
      7z a -mx=1 -p$encrypt_key $backup_dir/$i-wdb-Week$weekinfo.7z $backup_dir/$i-ddb-$dayinfo > /dev/null
			7zipErrorCheck $?

			timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
			echo "$timeinfo >  - (Weekly) Uploading -> Disaster Recovery Server..."
			scp -P $remote_port $backup_dir/$i-wdb-Week$weekinfo.7z $remote_user@$remote_ip:$remote_dir
		fi

    #Time Stamp closing the Packaging
		timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
    echo "$timeinfo > Pack: $i Complete <----------------"
	done

  #Cleapup
  #Time Stamp start of Cleanup
	timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
	echo "$timeinfo > Step 4: Clean Up"
  #for each database(i) that is not owned by postgres...
	for i in $databases; do
    #TODO move this too a clean up Step
    #removing uploaded database
		rm $backup_dir/$i-?db-*.*
    rm -R $backup_dir/$i-?db-*
    echo ""
    sleep 3
	done
  #Time stamp closing message
	timeinfo=`date '+%Y-%m-%d %H:%M:%S'`
	echo "$timedateinfo > ** Complete Clean Up **"
	echo "$timedateinfo > ---------------------------------------------------------------------"
} 2>&1 | tee $logfile

#Cleanup
gzip -9 $logfile
scp -P $remote_port $logfile.gz $remote_user@$remote_ip:$remote_dir
rm $logfile.gz
