#!/bin/bash
#_   _ _____ ___________   _____  ___
#| | | |_   _/  ___| ___ \ /  ___|/ _ \
#| |_| | | | \ `--.| |_/ / \ `--./ /_\ \
#|  _  | | |  `--. \  __/   `--. \  _  |
#| | | |_| |_/\__/ / |     /\__/ / | | |
#\_| |_/\___/\____/\_|     \____/\_| |_/
#Setting up a server, allows for switches to change the type of server deployed.
#Author	: Evert Bothma
#Created Date 	: October 2017
#functions
#Parameters input - usage

#Backing up the files that will be changed
cp /etc/network/interfaces /etc/network/interfaces.bak

#TODO error chekcing for $1 and $2
#TODO Add usages - sudo ./ethadd.sh <Physcial Server> <Public Last octicsajiovjcasio>
personalip=$(ifconfig eth0 | grep "inet addr" | awk '{print $2}' | awk -F '.' '{print $4}')

echo -e 'auto eth1' > /tmp/.eth.tmp
echo -e 'iface eth1 inet static'  >> /tmp/.eth.tmp
echo -e '\taddress 10.0.'$1.$personalip  >> /tmp/.eth.tmp
echo -e '\tnetmask 255.255.0.0' >> /tmp/.eth.tmp
echo -e '\tnetwork 10.0.0.0' >> /tmp/.eth.tmp
echo -e '\tbroadcast 10.0.255.255' >> /tmp/.eth.tmp

sudo sh -c 'cat /tmp/.eth.tmp >> /etc/network/interfaces'

# Restart networking service
sudo /etc/init.d/networking restart

# Show Results
ifconfig eth1
