#!/bin/bash
#_   _ _____ ___________   _____  ___
#| | | |_   _/  ___| ___ \ /  ___|/ _ \
#| |_| | | | \ `--.| |_/ / \ `--./ /_\ \
#|  _  | | |  `--. \  __/   `--. \  _  |
#| | | |_| |_/\__/ / |     /\__/ / | | |
#\_| |_/\___/\____/\_|     \____/\_| |_/
#Creating a specifed User with Key downloaded and injected
#Author	: Renier Rousseau
#Created Date 	: 05 October 2018

#Error check to ensure that the command has an argument.
if [ $# -ne 1 ] ; then
  #if there are not Parameters
  echo "Enter the name of the user you are trying to create."

else
  #Move though all the users to ensure that the one requested exsists.
  #flag for error if user does exist
  flag_user_exsists=0

  users_ls=`ls /home/`

  for u in $users_ls; do

    if [[ $1 = $u ]]; then
      #User found update flag_user_exsists
      flag_user_exsists=1

      #echo the bad news
      echo "User found! - Canceling User Creation."

      #exit
      exit
    fi
  done
  #flag_db_exsists is 0 - so user does not currently exsist
  if [[ $flag_user_exsists = 0 ]]; then
    #Create user
    sudo useradd -m -G sudo -s /bin/bash $1

    #Generating and assinging the password for the user.
    echo $(</dev/urandom tr -dc A-Za-z0-9 | head -c 20) > ~/passwd.txt
    sudo mv ~/passwd.txt /home/$1/passwd.txt
    echo "$1:$(cat /home/$1/passwd.txt)" | sudo chpasswd $1


    #get the key from a remote host and add it too the users authorized_keys file
    #get sshpublic Key.
    wget https://raw.githubusercontent.com/hispsa-Infra/scripts/master/setup/sshkeys/$1/authorized_keys
    sudo mkdir /home/$1/.ssh
    mv authorized_keys /tmp/.authorized_keys
    sudo mv /tmp/.authorized_keys /home/$1/.ssh/authorized_keys

    #Changing the owner ship
    sudo chown -R $1:$1 /home/$1/.ssh/*
    sudo chown -R $1:$1 /home/$1/.ssh/

    echo "User - $1 - has been added"
  fi
fi
